###########################################################################
# Copyright (C) 2013 Phani Vadrevu                                        #
# pvadrevu@uga.edu                                                        #
#                                                                         #
# Distributed under the GNU Public License                                #
# http://www.gnu.org/licenses/gpl.txt                                     #
#                                                                         #
# This program is free software; you can redistribute it and/or modify    #
# it under the terms of the GNU General Public License as published by    #
# the Free Software Foundation; either version 2 of the License, or       #
# (at your option) any later version.                                     #
#                                                                         #
###########################################################################
features = (
["dump_id",
"vt_month_shelf",
"corrupt",
"host_malware_downloads", 
"host_suspicious_downloads", 
"host_benign_downloads", 
"host_total_downloads", 
"host_malware_ratio", 
"host_suspicious_ratio", 
"host_benign_ratio", 
"host_avg_av_labels", 
"host_avg_trusted_labels", 
"host_unknown_hashes", 
"host_total_hashes", 
"host_unknown_hash_ratio", 
"twold_malware_downloads", 
"twold_suspicious_downloads", 
"twold_benign_downloads", 
"twold_total_downloads", 
"twold_malware_ratio", 
"twold_suspicious_ratio", 
"twold_benign_ratio", 
"twold_avg_av_labels", 
"twold_avg_trusted_labels", 
"twold_unknown_hashes", 
"twold_total_hashes", 
"twold_unknown_hash_ratio", 
"server_ip_malware_downloads", 
"server_ip_suspicious_downloads", 
"server_ip_benign_downloads", 
"server_ip_total_downloads", 
"server_ip_malware_ratio", 
"server_ip_suspicious_ratio", 
"server_ip_benign_ratio", 
"server_ip_avg_av_labels", 
"server_ip_avg_trusted_labels", 
"server_ip_unknown_hashes", 
"server_ip_total_hashes", 
"server_ip_unknown_hash_ratio", 
"bgp_malware_downloads", 
"bgp_suspicious_downloads", 
"bgp_benign_downloads", 
"bgp_total_downloads", 
"bgp_malware_ratio", 
"bgp_suspicious_ratio", 
"bgp_benign_ratio", 
"bgp_avg_av_labels", 
"bgp_avg_trusted_labels", 
"bgp_unknown_hashes", 
"bgp_total_hashes", 
"bgp_unknown_hash_ratio", 
"hash_life_time", 
"num_dumps_with_same_hash", 
"hash_daily_dump_rate_per_client", 
"estimated_clients_with_same_hash", 
"referer_exists", 
"host_name_exists", 
"extension_class",
"url_length", 
"directory_depth", 
"sha1", 
"host", 
"url_malware_downloads", 
"url_total_downloads", 
"url_distinct_sha1s", 
"url_struct", 
"url_struct_malware_downloads", 
"url_struct_total_downloads", 
"url_struct_distinct_sha1s"])
